name: "Check if base image has been updated"
description: "GitHub Action to check if the base Docker image has been updated"
author: Mike Jones

inputs:
  base-image:
    description: "Docker base image, if not specified, action will try and extract it from the Dockerfile.  This will currently fail if there are multiple FROM statements"
    required: false
  image:
    description: "Docker image"
    required: true
  gh_token:
    description: GITHUB_TOKEN
    required: true
outputs:
  needs-updating:
    description: "True or false"
    value: ${{ steps.run-script.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: run-script
      run: |
        base=${{ inputs.base-image }} image=${{ inputs.image }} gh_token=${{ inputs.gh_token }} ${{ github.action_path }}/check.sh
      shell: bash
